create table "public"."circle" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "circle_owner" character varying
);


alter table "public"."circle" enable row level security;

CREATE UNIQUE INDEX circle_pkey ON public.circle USING btree (id);

alter table "public"."circle" add constraint "circle_pkey" PRIMARY KEY using index "circle_pkey";

grant delete on table "public"."circle" to "anon";

grant insert on table "public"."circle" to "anon";

grant references on table "public"."circle" to "anon";

grant select on table "public"."circle" to "anon";

grant trigger on table "public"."circle" to "anon";

grant truncate on table "public"."circle" to "anon";

grant update on table "public"."circle" to "anon";

grant delete on table "public"."circle" to "authenticated";

grant insert on table "public"."circle" to "authenticated";

grant references on table "public"."circle" to "authenticated";

grant select on table "public"."circle" to "authenticated";

grant trigger on table "public"."circle" to "authenticated";

grant truncate on table "public"."circle" to "authenticated";

grant update on table "public"."circle" to "authenticated";

grant delete on table "public"."circle" to "service_role";

grant insert on table "public"."circle" to "service_role";

grant references on table "public"."circle" to "service_role";

grant select on table "public"."circle" to "service_role";

grant trigger on table "public"."circle" to "service_role";

grant truncate on table "public"."circle" to "service_role";

grant update on table "public"."circle" to "service_role";


